### ISSUE TITLE
Finish Feedback Modal in Contribution Page

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1003]
- [x] GET `/api/assembly/{assemblyID}/campaign/{campaignID}/contribution/{contriutionID}/feedback`

- [ ] Connect the Stars to the average of feasibility, need and benefit score resulting from above.  
- [x] List individual feedback, including only those that either have given one of the three scores or provided a textual feedback. Each item should show:  
      1. The three scores if there are
      2. The textual feedback if there is one (might contain HTML, render at least the formatting tags - e.g., bolds, italics, paragraphs). We can use the square box for themes or something nicer.
      3. Status and type as a label
      4. User profile box (like in comments, only if type===`MEMBER`).  
 - [x] If the user who is reading this is not one of the authors of the idea/proposal, do not show feedbacks that have `status !== 'PUBLIC'` or `type='TECHNICAL_ASSESSMENT'`
- [x] For each textual feedback, put also the score

**Comment by cdparra** [comment]
@gvescu what clarification you need?

**Comment by gvescu** [comment]
1) That API endpoint returns an array of feedbacks, right? I tested it in one case and every object that came had similar properties with some differences.
2) AVG of feasibility, need and benefit: It will be calculated? On that same case that I've tested the objects didn't had those properties. Actually it tries to obtain those values from `proposal.stats.averageNeed`, `proposal.stats.averageFeasibility` & `proposal.stats.averageBenefit`.
3) If I understand correctly, bellow the stars it should display the objects that came from the endpoint, right? I found some that had a property called `textualFeedback`.

**Comment by cdparra** [comment]
(1) => Yes. It returns all the FEEDBACKS on a specific contribution. Including the simple `ups` and `downs` (whenever I upvote/downvote/flag a contribution, a feedback is created). Let's show only the ones that either have a `textual_feedback`, or a score on one of the feasibility, need, benefit trio. We could also show a small summary of the ups and downs. 
(2) => I thought the endpoint had the average. If not, let's calculate them and I will see if I can add averages later. 
(3) => Yes. The idea is to show the ones that either have a textual feedback or the scores.
