### ISSUE TITLE
Fix contribution export of `selected contributions`

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1031]
- [X] Fix how query params are sent (e.g., array of values are sent by duplicating the same query param, not giving the value of an array
- [X] Make sure the frontend downloads the CSV when gets it
- [ ] Add extended doc format select to modals in campaign and WG
- [x] Add explanation about emails being sent
- [x] Translations

**Comment by yolile** [comment]
this seems to be done
![image.png](https://images.zenhubusercontent.com/5a43ab508a75884b908c43f3/d5889add-73e5-4d93-8cf1-10a11d0c076f)
