### ISSUE TITLE
Bug: notifications components shows one unread but all are read in the list

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1037]
make sure unreads are above

![image.png](https://images.zenhubusercontent.com/55ca3bba4f7a08fbb7f43c8a/2133f762-7732-4feb-bf51-f844b909c67a)

**Comment by yolile** [comment]
I think this is solved know, the problem was that the notification service was not returning the notifications in creation order so the non read notificaiton was not visible because it was at the last in the list. Changes already in develop
