### ISSUE TITLE
Notifications shows number of unread but none is shown in box below

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1040]
How to reproduce: 

- Change read of existing notification_event_signal_user from TRUE to FALSE 

![image.png](https://images.zenhubusercontent.com/55ca3bba4f7a08fbb7f43c8a/a9504548-8e98-4e21-ab57-36c172cf8e65)

![image.png](https://images.zenhubusercontent.com/55ca3bba4f7a08fbb7f43c8a/a84f622b-4eb
6-4a97-be15-e9d0f66c93bd)

**Comment by mitar** [comment]
So this has been already fixed? Can you leave a comment when closing an issue explaining why (like, "I could not reproduce it anymore", or "I know we fixed this in the past", etc.).

**Comment by yolile** [comment]
This is already fixed
