### ISSUE TITLE
Bug: Idea description not shown

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1061]
![image.png](https://images.zenhubusercontent.com/55ca3bba4f7a08fbb7f43c8a/f96114a4-e79d-48db-85a4-11dd41e72423)

**Comment by gvescu** [comment]
The API doesn't return the required field for the trustedHtml function, which is proposal.text that returns richText

**Comment by cdparra** [comment]
API now returns the `text` field
