### ISSUE TITLE
Integrate Appcivist Client with PeerDoc project

### ISSUE THREAD

**Issue by loorely** [socialappslab/appcivist-pb-client#1067]
## Describe the problem/story
1. Add `peerDoc` button to proposal page behind google doc and etherpad links. 
2. Add `peerDoc` editor to appcivist as an iframe
3. When `extendedPadText` is PEERDOC type, embed peerdoc url adding parameters required by the iframe.

**Comment by cdparra** [comment]
To complete the integration on the AppCivist side: 
- [ ] The frontend should show something like the Etherpad modal, asking for the user to choose between providing th baseUrl and hexKey of a peerdoc server, or simply using the configured server in our backend
- [ ] The backend should be able to read these parameters and then create the appropriate peerdoc.

**Comment by cdparra** [comment]
Will open the last comment as new issues and close this one now
