### ISSUE TITLE
Filter by choosing my ideas or my proposals has translation issues

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1085]
4.  When I click on the filter "My proposals", I get 
No $$$ myProposals $$$s in this space yet

"My ideas" goes to
No myIdeass in this space yet

**Comment by yolile** [comment]
not an issue anymore

![image.png](https://images.zenhubusercontent.com/5a43ab508a75884b908c43f3/3e3dd7a3-4ea0-4881-823c-0f73496e7d42)
