### ISSUE TITLE
cogwheel not showing menu options for member when user is not coordinator 

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1095]
![image.png](https://images.zenhubusercontent.com/55ca3bba4f7a08fbb7f43c8a/c4b98043-87fe-44ca-911a-26bb3480a6d6)

**Comment by yolile** [comment]
it seems like the button is never shown now https://github.com/socialappslab/appcivist-pb-client/blob/master/app/v2/partials/campaign/dashboard.html
