### ISSUE TITLE
Review github alerted vulnerability

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1138]
![image.png](https://images.zenhubusercontent.com/55ca3bba4f7a08fbb7f43c8a/7d78e3d1-53c4-4c89-8f07-95453009aea3)

**Comment by yolile** [comment]
still an issue see open PRs https://github.com/socialappslab/appcivist-pb-client/pulls?q=is%3Aopen+is%3Apr+label%3Adependencies

**Comment by yolile** [comment]
all the PRs were merged and the security issues fixed, however, there is still one security issue about ecstatic library, that is used by http-server in appcivst, which is already in its more recent version, so we cannot resolve that issue for now

**Comment by mitar** [comment]
Thanks!
