### ISSUE TITLE
When embedding PeerDoc, make initially more space

### ISSUE THREAD

**Issue by mitar** [socialappslab/appcivist-pb-client#1154]
When embedding PeerDoc, initially, the height is very small (10px or so?), when everything is loading. This prevents a loading icon to be shown because you do not see it. I would propose that the initial iframe height is 150px, and then after PeerDoc loads it will send message to AppCivist to adapt to real height.

**Comment by yolile** [comment]
seems to be fixed https://github.com/socialappslab/appcivist-pb-client/blob/9c34b279343b6ea183fc73d220126f935fd21a13/app/v2/partials/contribution/page.html#L557
