### ISSUE TITLE
 Logged-in Campaign Page cogwheel on proposal card and cogwheel on draft card are truncated.  Other cogwheels are ok.

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1160]
@cdparra 

<img width="1440" alt="screen shot 2018-05-10 at 5 48 18 pm" src="https://user-images.githubusercontent.com/5572598/39893514-5ebc7a66-547a-11e8-8501-0b8d12df1ed0.png">

<img width="1440" alt="screen shot 2018-05-10 at 5 47 30 pm" src="https://user-images.githubusercontent.com/5572598/39893528-6a5e5ae2-547a-11e8-84c8-09c4631e0e13.png">

**Comment by yolile** [comment]
not an issue anymore
