### ISSUE TITLE
New translations for proposal without document notice

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1194]
6.  Change message for non-authors or logged out authors:

Change:
Se você é um autor desta [type of contribution], entre no site para acessá-la ("Iniciar Sessão", acima). Se você não é um autor, peça aos autores para adicionar você e depois entre no site.

If you are an author of this [type of contribution], sign in to access it ("Sign in", above).  If you are not an author, ask its authors to add you and then sign in."

=> new version:

"Se esta [type of contribution] está compartilhada com você, faça login para acessá-la ("Iniciar Sessão", acima). Se ela não está, peça a alguém listado para compartilhá-la com você e depois faça login."

If this [type of contribution] is shared with you, sign in to access it ("Sign in", above).  If it is not, ask someone listed to share it with you and then sign in."

**Comment by yolile** [comment]
I think this is done
![image.png](https://images.zenhubusercontent.com/5a43ab508a75884b908c43f3/f9c8ef94-144a-49f2-8b92-7dbd79238c00)
