### ISSUE TITLE
Last Activity not refreshing

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1246]
![](https://i.gyazo.com/5e7f5e72b6f64b423aa1b79f866b5cdb.gif)

**Comment by gvescu** [comment]
Not quite sure how to proceed with this one.

After making changes to the peerdoc, the endpoint doesn't seem to return any changes. Therefore, the Last Updated of the proposal won't change.
![chrome_2018-07-03_00-14-48](https://user-images.githubusercontent.com/2433926/42198486-33a6012a-7e56-11e8-8d93-af13993d3211.png)

**Comment by gvescu** [comment]
@cdparra I've tested it again. If I change anything else other than the Peerdoc it updates fine. Seems like Peerdoc isn't updating the lastUpdate field when it saves.

**Comment by cdparra** [comment]
@gvescu any progress on this working with @yolile ? We need to know if this an error: 
(1) On the frontend (seems unlikely for what  @gvescu reported) 
(2) Our backend (can you check @yolile? You will need to coordinate tests with @gvescu)
(3) On peerdoc's side.

**Comment by cdparra** [comment]
After further testing we realized that the problem is on Peerdoc's side, which is sending the information with the field lastUpdate rather than lastActivity

```
[debug] application - AUTH: request uri: /api/contribution/7tx9mGPWfkME2dRH3?lastUpdate=2018-07-09T17%3A04%3A04.795Z
....
[info] application - Updating contribution from external service based on document ID: 7tx9mGPWfkME2dRH3
[info] application - All parameters are empty. Nothing to update
```

**Comment by cdparra** [comment]
After further testing, this issue is only visible in the testing version of appcivist, probably because the testing version of peerdoc is not updated to the latest version that contains the fix.
