### ISSUE TITLE
Change message displayed instead of peerdoc for Pubic Drafts

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1263]
should read => "Esta proposta tem o status de Rascunho Público. Toda a comunidade Unifesp pode ver e comentar sobre um Rascunho Público, mas só quem está compartilhado pode editar."  This message needs to remain at the bottom of the screen so that viewers can scroll thought longer proposals to read them.

**Comment by gvescu** [comment]
This was solved with #1268

**Comment by jamesholston** [comment]
@gvescu @cdparra Add the word "Unifesp" to the banner, as above ("... Toda a comunidade Unifesp pode ...").

In current version, "Unifesp" is missing.

**Comment by cdparra** [comment]
The text is stored in the database as a configuration. I have updated the configuration now. It previously read "toda a comunidade universitaria". I don't really see a difference between this version and the previous one, and yet it took time from us to look what was this about, whether it was code related or configuration in database, etc. 

I think we need adopt an approach by which changes on text are this minimal, are simply be ignored, at least until we have a minimal backoffice that would allow coordinators to update these texts on their own. 

Even minimal, they take time and attention from other things that are much more important.
