### ISSUE TITLE
Email update modal does not appear on login for users with @ldap.com emails

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1269]
The email verification process is working well, except for two issues.  The first I document in this issue and the second in the next issue.
1.  When the user has an @ldap.com email, she is supposed to receive the alert to update. For new users, this alert should appear immediately after the research consent form.  However, it does not appear even after waiting many minutes.  Thus, its failure to appear is not a matter of some time delay.  Moving around in the campaign page -- clicking on My Proposals, for example -- did not get it to appear either.  However, I was able to get the email alert modal by going in and out of My Settings.  Once in My Settings, the red warning was visible asking to update.  I did not do so, but returned to the Campaign page.  As soon as I did, the email alert modal popped up.  I then followed its instructions, returning to the profile page, changed the email, and updated.  Once I got the email verification modal, all worked as intended.  

So, for new users, the email verification modal needs to appear _immediately_ after the research consent form.  It does not help matters much to have to go into My Settings first, because many users don't go there in a timely fashion, and until they do, they won't get email.

I was not able to find anyone who had already registered but who still had a @ldap.com.  This type of user will not get the research consent form upon login, but should get the email verification modal as soon as the logged-in campaign page appears.

**Comment by cdparra** [comment]
@jamesholston can you provide some examples of users who are experiencing this issue?

**Comment by jamesholston** [comment]
I think the user below is an example, or was an example.  I will try to find others tomorrow as today is a holiday here.


![screen shot 2018-06-29 at 3 05 14 pm](https://user-images.githubusercontent.com/5572598/42467231-b9c1f116-8387-11e8-9f5d-1fba2872fa11.png)
