### ISSUE TITLE
Add field to add the proposal to a WG in proposal page

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1319]
As with themes and keywords, add a button to select the WG of the proposal. 
![image](https://user-images.githubusercontent.com/630150/45335856-0ade4380-b536-11e8-82e0-d996c1195bf4.png)

This should be displayed if: 
1. The configuration `appcivist.campaign.working-group-proposals` === `ENABLED` (by default is DISABLED)
2. If the configuration `appcivist.campaign.working-group-number-limit` === 1, use a select (default is 1 if this config does not exist)
3. If configuraiton in (2) is > 1, then limit to that number as it is with themes

The list of WG to display should be the WGs of the campaign. 
When selecting a WG, the proposal should be added to that WG.

**Comment by yolile** [comment]
The feature was implemented with the Asign to Working Group button visible for the coordiators, without a config
