### ISSUE TITLE
Custom fields not loaded in editing mode of the proposal

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1321]
![image.png](https://images.zenhubusercontent.com/55ca3bba4f7a08fbb7f43c8a/b44ee1a0-6014-4a5b-8e95-41327935682b)

**Comment by cdparra** [comment]
I think this was already clarified via slack. moving back to sprint. @gvescu @loorely

**Comment by mitar** [comment]
So this is now working?

**Comment by yolile** [comment]
Fixed
