### ISSUE TITLE
First iteration of the UI starting with the Assembly Space

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#3]
Potentially, think about: 
* The Assembly Space (i.e., the assembly homepage, what should be there?)
* The Campaign Space (i.e., the page of the campaign process, e.g., participatory budgeting for vallejo 2015, what should be there?)
* The Working Group Space (i.e., main page for groups to work on)
* [OPTIONAL] The Contributions Space (page where contributions to an assembly can be seen, discussed, made, categorized, reorganized. Depending on user, these functionalities will be ON or OFF)

**Comment by animeshpathak** [comment]
I assume this will be a basic UI, to be polished by an expert?

**Comment by cdparra** [comment]
Yes, will be basic. There is a boilerplate we have prepared with @joseanmp in this [repository][1], which will be extended to include what we call the "Assembly Space" this week. 

The Assembly Space is the home page of an assembly ("Neighborhoods united for PB", "PB Steering Commitee of Vallejo", etc.), displaying a summary of contributions (ideas, questions, comments, issues) made by users, the list of active campaigns (e.g., "Participatory Bugdeting 2015") and the internal working groups working in proposals. 

[1]: https://github.com/socialappslab/appcivist-pb-client

**Comment by cdparra** [comment]
First ideas for the UI are in this [Brainstorming Google Drive Folder](https://drive.google.com/folderview?id=0B7ShzcEnCJFNNjZISUFEWF9HN0E&usp=sharing). This issue is about starting the demo with the a demo of the Assembly Space

**Comment by cdparra** [comment]
First iteration, partially connected to the API, done.
