### ISSUE TITLE
Integrate forgot password functionality

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#322]
@jorgeramirez for the workflow, check this comment on the backend feature issue: https://github.com/socialappslab/appcivist-platform/pull/324#issuecomment-281710722

**Comment by jorgeramirez** [comment]
@cdparra can you elaborate on this one? what is the flux and endpoint that we are going to use here?

**Comment by cdparra** [comment]
More clarifications: 
1. `POST /api/user/password/reset` sends an email with the reset URL to the user email, and then redirects to the backend index (i.e., platform.appcivist.org) 
2. The pattern of the URL that the user receives is: `applicationBaseUrl`+`/user/password/reset/`. applicationBaseUrl is configured in the backend and corresponds to the client base URL (we actually need to change this and allow the client to establish what its base url is) 
3. So, frontend needs to implement `FRONTENDBASEURL/#//user/password/reset/:token`. 
4. Future versions will allow the FRONTEND to say what its reset base url is

**Comment by jorgeramirez** [comment]
@cdparra Just to keep in mind before running QA: there is an error in the backend, but the frontend is complete.
