### ISSUE TITLE
Add icon for attachments that are not images

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#344]
![image](https://cloud.githubusercontent.com/assets/630150/21786567/35ce3244-d6a3-11e6-87d4-1e0a8a2a98aa.png)

**Comment by jorgeramirez** [comment]
this seems to work. Can reproduce the error.

<img width="1149" alt="screen shot 2017-03-27 at 9 39 48 am" src="https://cloud.githubusercontent.com/assets/732626/24359137/6ff80e8a-12d1-11e7-9f42-b80803c7bfeb.png">
