### ISSUE TITLE
Show plain text not working as expected

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#412]
By default, we should display the formatted html. Instead, we show the plain text and then show the HTML markups when we click on see as plain text. When clickin this checkbox, use the field "plain_text" 

![image](https://cloud.githubusercontent.com/assets/630150/23012685/223af34a-f406-11e6-9db5-0428b8c69a2a.png)

**Comment by jorgeramirez** [comment]
@cdparra the ContributionFeedback model doesn't have the field plain_text, I only found the field textual_feedback where the HTML text is saved.
