### ISSUE TITLE
Implement the assembly homepage

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#417]
- [x]  List ongoing campaigns
- [x] List past campaigns
- [ ] List WGs per campaign

**Comment by cdparra** [comment]
Final design to implement. Le't use the landing page as template. In the first section, if the assembly has a cover and it the configuration `"assembly.landing-page-show-cover" === TRUE`, then show the cover as backgorund with the green on top, with opacity at 70%

![appcivist assemble landing page v2 green](https://cloud.githubusercontent.com/assets/630150/23550298/04b20e9a-ffef-11e6-8c1d-1360d675697e.jpg)

[This google drive folder contains assets that can be used for the development](https://drive.google.com/open?id=0B7ShzcEnCJFNcVBYMEtoNU9iU3c), including 

1. JPGs of the new design (see the ones name `AppCivist Assemble Landing Page v1 (green).jpg` [english] and `AppCivist Assemble Landing Page v2 (green).jpg` [french])
2. SVGs that can be helpful to copy content in something more akin to HTML format (same names, use the v1 for english)
3. A CSS exported from sketch that contains some of the styles to reuse (`AppCivist Assemble Landing Page v1.css`

**Comment by jorgeramirez** [comment]
@cdparra TODO

- Assembly cover/background
- Working group list view
- Sign Up button based on assembly configuration
- Sign In redirects to shortname/login
