### ISSUE TITLE
Finish up creation of assemblies, campaigns and working groups

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#433]
- [ ] Review the creation forms and test, making them work

Based on comments and notes resulting from the debugging of these functionalities: #335

**Comment by jorgeramirez** [comment]
Continuation of https://github.com/socialappslab/appcivist-platform/issues/335

**Comment by cdparra** [comment]
@jorgeramirez make sure you add the following: 

- [ ] Send invitations checkbox (to create Assembly and Working Group) (property "sendInvitations" of the model)
- [ ] Organizations (to create Assembly). Like attachments for Proposals, each organization is a resource with title, description, URL. The interaction should be "Add organization" => Name, Description, Upload Logo fields appear => They are added as a resource to the "organizations" array of the assembly model.

**Comment by jorgeramirez** [comment]
@cdparra Currently campaign creation seems to work. As a side note, I added support for ES 2015 through babel.

**Comment by jorgeramirez** [comment]
@cdparra  I will put this on hold. To start working on #417
