### ISSUE TITLE
Comment box in group page is now smaller

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#479]
![image](https://cloud.githubusercontent.com/assets/630150/23243200/1a1b625c-f95c-11e6-91da-fd8a9be69b99.png)

Temporary fix with: style="float:none" on fieldset, but should be considered in the styles
![image](https://cloud.githubusercontent.com/assets/630150/23243215/35e7b648-f95c-11e6-94d6-5e224ac50f80.png)

**Comment by jorgeramirez** [comment]
this is fixed in PR #486
