### ISSUE TITLE
On Edit and Creation form for Proposal and Ideas, show custom fields and a control to display them in proposal page

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#506]
Show custom fields values defined in the parent campaign and the currentComponent in the proposal page and the create proposal or create idea form.

**Comment by cdparra** [comment]
refer to appcivist-platform/issue#382 for details about the endoints you need to use

**Comment by cdparra** [comment]
Visually: here is a mockup

![image](https://cloud.githubusercontent.com/assets/630150/24117110/a95a6514-0d87-11e7-842f-57afbcbe9ca1.png)

Basically: 
- Using endpoint `GET       /api/space/:sid/field`, you would read what custom fields are needed for a proposal (you should read the list of fields listed on the campaign resource space and on the current component resource space
- The field definition will identify what type of field this is (TEXT, FILE, NUMBER) and the limit that we should apply to it (a number) that is qualified by a limitType (WORDS, CHARS, FILE_SIZE)
- We use the previous to show fields in the proposal creation form and to display values for the fiels in the proposal page
- The values come from `GET /space/:id/fieldvalue`. There are also POST, DELETE and PUT endpoints for these values, that should be used when editing proposals.

**Comment by cdparra** [comment]
Visually: here is a mockup

![image](https://cloud.githubusercontent.com/assets/630150/24117110/a95a6514-0d87-11e7-842f-57afbcbe9ca1.png)

Basically: 
- Using endpoint `GET       /api/space/:sid/field`, you would read what custom fields are needed for a proposal (you should read the list of fields listed on the campaign resource space and on the current component resource space
- The field definition will identify what type of field this is (TEXT, FILE, NUMBER) and the limit that we should apply to it (a number) that is qualified by a limitType (WORDS, CHARS, FILE_SIZE)
- We use the previous to show fields in the proposal creation form and to display values for the fiels in the proposal page
- The values come from `GET /space/:id/fieldvalue`. There are also POST, DELETE and PUT endpoints for these values, that should be used when editing proposals.

**Comment by jorgeramirez** [comment]
@cdparra currently edition works. Creation still in-progress. Also, there are some weird issues with the fields not rendering sometimes. It started happening after merging develop. Also, tinymce editor disappears with no clear reason.
