### ISSUE TITLE
Hide etherpad timeline after iframe is loaded

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#520]
Check if the following is possible and implement this for the readOnly case: 
- [ ] After etherpad is fully loaded, call `window.document.getElementById("timeslider").style="display: none;"` to hide the timeline and avoid giving access to non public revisions

**Comment by jorgeramirez** [comment]
@cdparra due to cross-domain security policy, this can't be achieved.

**Comment by cdparra** [comment]
@jorge I will open up a new ticket to explore alternatives to etherpad, including GDocs
