### ISSUE TITLE
"See my proposals" filter + create proposal and my proposals UX improvements 

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#524]
- [x] Add "See my proposals" filter (proposals where user is in the author array)
- [x] When clicking on "See my proposals", show proposals (with any status) for which the user is in the author array 
- [x] After creating a proposal, redirect to proposal page
- [x] If we are on a campaign that does not allow individual proposals (Config `"appcivist.campaign.enable-individual-proposals"` = `FALSE` or `null`) and the user is not a member of any group in the campaign, replace "Add new proposal" button with label "Join a Working Group to create proposals"
- [x] Add "Add new proposal" button in Working Group Dashboard

**Comment by jorgeramirez** [comment]
- "See my proposals" where should be added? 
-  What is the endpoint for requesting to join a working group?

**Comment by cdparra** [comment]
@jorgeramirez 
- [ ] Place the "See my proposals" link in the sidebar menu and also under the filter section
- [ ] [POST Group Membership Request](https://platform.appcivist.org/api/doc#!/04_membership%3A_Membership_management_(for_assemblies_and_working_groups)/createMembershipRequest)

**Comment by jorgeramirez** [comment]
- [ ] proposal-search-box and pagination-widget should be integrated in order to make filtering work again

**Comment by jorgeramirez** [comment]
@cdparra currently Working Group dashboard does have the "Add new proposal" button.

<img width="385" alt="screen shot 2017-05-13 at 6 16 39 pm" src="https://cloud.githubusercontent.com/assets/732626/26029648/6a69e220-3808-11e7-995b-d024d32a957d.png">

**Comment by cdparra** [comment]
@jorgeramirez I think I might have added it myself or we have dealt with this in another ticket. Marking this as done then.
