### ISSUE TITLE
Make sure etherpad is embedded and shown in the User's or Browser's Language

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#552]
As per [etherpad documentation](https://github.com/ether/etherpad-lite/blob/7ecf240d9e46ac41259100bf83242ca7b8fc205b/doc/localization.md) 
```
Client-side

We use a language cookie to save your language settings if you change them. If you don't, we autodetect your locale using information from your browser. Now, that we know your preferred language this information is feeded into a very nice library called html10n.js, which loads the appropriate translations and applies them to our templates, providing translation params, pluralization, include rules and even a nice javascript API along the way.
```

- [ ] Make sure we set the cookie or change the browser's language settings for the session (see the `ngTranslateLanguageSelect` directive (in the old directives folder) for an example

**Comment by jorgeramirez** [comment]
@cdparra I think we need to change [etherpad-lite](https://github.com/ether/etherpad-lite) to support query parameter `locale=<code>`. So that we can specify locale for embedded pad.
