### ISSUE TITLE
Hide custom information section if there are no custom fields

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#617]
![image](https://cloud.githubusercontent.com/assets/630150/25565656/20c86d36-2d99-11e7-8946-4cbea1196415.png)

Under that section, you will see there is a "ng-repeat" that points to an array. If that array is empty, do not show this title

**Comment by JoaquinGimenez1** [comment]
The solution I found was add `<li ng-show="!events.length"></li>` after the ng-repeat and doesn't show anymore the Custom Information label. Working on testing this new feature before create a pull request

**Comment by cdparra** [comment]
Fixed in 3d6b929cca5c7b637ec2077f9951bc6485398988
