### ISSUE TITLE
Fix resizing of idea cards

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#706]

**Comment by jorgeramirez** [comment]
@cdparra can you elaborate on this one?

**Comment by jorgeramirez** [comment]
It seems that the fix I'd done went away, I will check it out.

**Comment by cdparra** [comment]
@jorgeramirez [![here is what the issue looks like](https://gyazo.com/82da174c0446f0a400309b9353b76612/raw)](https://gyazo.com/82da174c0446f0a400309b9353b76612)
