### ISSUE TITLE
Do not delete IDs of emergent themes that already exists, put them into existingThemes

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#708]

**Comment by jorgeramirez** [comment]
@cdparra can you elaborate on this one?

**Comment by cdparra** [comment]
For emergentThemes, the idea is that users can reuse existing emergentThemes or create new ones. Right now, there is a delete theme_id that prevents the backend from detecting that a theme is existing @jorgeramirez
