### ISSUE TITLE
Bug: Forgot Password Link based url must be of the current site not fixed to pb.appcivist.org

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#781]

**Comment by gvescu** [comment]
Can't reproduce this bug, @cdparra 

Is this the "Forgot password?" link on the login screen? On the code it has a `/#/v2/user/password/forgot` href, and the form itself uses an API endpoint.

**Comment by cdparra** [comment]
@gvescu there is an additional attribute that must be added to the body of the request that tells the server what the correct base URL is: 
```json
{
    "email": "<user email>", 
    "configUrl": "https://pb.appcivist.org/#/v2/user/password/reset/"
}
```

If the attribute is not added, then the server uses the configured URL in the configuration of the backend, which was configured incorrectly, which is fixed now. But even if fixed, we should used the  API properly and include the `configUrl`  property in the request.

**Comment by cdparra** [comment]
Went ahead and provided a quick hotfix for this. See 11a399864fbef2c1adc86872f7741b90dd8e9d3d
