### ISSUE TITLE
Allow adding attachments to ideas

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#908]

**Comment by yolile** [comment]
This seems to be implemented already: 
![image.png](https://images.zenhubusercontent.com/5a43ab508a75884b908c43f3/f602b086-52dc-4cb5-ba8c-ca27b04a4750)

https://github.com/socialappslab/appcivist-pb-client/blob/9c34b279343b6ea183fc73d220126f935fd21a13/app/v2/partials/contribution/page.html#L725

**Comment by mitar** [comment]
Are you sure this is to ideas and not to some other contributions?

**Comment by yolile** [comment]
looking at the code https://github.com/socialappslab/appcivist-pb-client/blob/9c34b279343b6ea183fc73d220126f935fd21a13/app/v2/partials/contribution/page.html#L727 there is not validations regarding the contributionType, so it is shown in both, proposals and ideas

**Comment by mitar** [comment]
Thanks for checking.
