### ISSUE TITLE
Add info for contributions coming from Facebook on idea cards

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#911]

**Comment by gvescu** [comment]
The DB is on an old evolution and any attempt to upgrade it went wrong (authentication returns 401 even when is the correct password, that may be some migration missing, but who knows which).

I will do it anyways as it's adding visual elements if some conditions are met, but I may not test it properly.

**Comment by cdparra** [comment]
See comment on #912
