### ISSUE TITLE
Link non member authors to their profiles in facebook if that's where the post comes from

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#912]

**Comment by gvescu** [comment]
Same issue as #911.

The DB is on an old evolution and any attempt to upgrade it went wrong (authentication returns 401 even when is the correct password, that may be some migration missing, but who knows which).

I will do it anyways as it's adding visual elements if some conditions are met, but I may not test it properly.

**Comment by cdparra** [comment]
Just shared a new backup to ensure testing is done right.

**Comment by cdparra** [comment]
Moved back to sprint for @gvescu to work on it as soon as possible.

**Comment by cdparra** [comment]
@gvescu now that you have a new DB, I am moving this to the top of the sprint
