### ISSUE TITLE
Show comments dissapear from campaign dashbaord and WG dashboard

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#995]
![image.png](https://images.zenhubusercontent.com/55ca3bba4f7a08fbb7f43c8a/78275147-3392-43be-bd02-94a152d7d0f7)

**Comment by gvescu** [comment]
This is old behavior from the old design. The comment box at the bottom hides after the grid reaches Bootstrap's lg size (>1200px). I can fix it, but apparently we need to restore this old behavior with the new design, so I have to redesign the grid.
